// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: srcjflexcup/Lexer.flex

import java_cup.runtime.Symbol;
import SymbolTable.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900"+
    "\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00\1\u4f00\1\u5000"+
    "\1\u5100\1\u5200\3\u0100\1\u5300\1\u5400\1\u5500\12\u1f00\4\u0100"+
    "\1\u5600\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900"+
    "\2\u1f00\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00"+
    "\42\u1f00\1\u0100\1\u5f00\1\u6000\11\u1f00\1\u6100\24\u1f00\1\u6200"+
    "\1\u6300\1\u1f00\1\u6400\1\u6500\1\u6600\1\u6700\2\u1f00\1\u6800"+
    "\5\u1f00\1\u6900\1\u6a00\1\u6b00\5\u1f00\1\u6c00\1\u6d00\2\u1f00"+
    "\1\u6e00\1\u1f00\1\u6f00\14\u1f00\1\u7000\4\u1f00\246\u0100\1\u7100"+
    "\20\u0100\1\u7200\1\u7300\25\u0100\1\u7400\34\u0100\1\u7500\14\u1f00"+
    "\2\u0100\1\u7600\5\u1f00\23\u0100\1\u7700\u0aec\u1f00\1\u7800\1\u7900"+
    "\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\16\0\4\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\12\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\4\11\1\35\25\11\3\5\1\36\1\37\1\5\1\40"+
    "\1\41\1\11\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\2\11\1\50\1\51\1\52\1\53\1\54\1\11\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\3\11\1\5\1\63"+
    "\2\5\6\0\1\64\32\0\2\5\4\11\4\5\1\11"+
    "\2\5\1\0\7\5\1\11\4\5\1\11\5\5\27\11"+
    "\1\5\37\11\1\5\u01ca\11\4\5\14\11\16\5\5\11"+
    "\7\5\1\11\1\5\1\11\21\5\160\0\5\11\1\5"+
    "\2\11\2\5\4\11\1\5\1\11\6\5\1\11\1\5"+
    "\3\11\1\5\1\11\1\5\24\11\1\5\123\11\1\5"+
    "\213\11\1\5\5\0\2\5\246\11\1\5\46\11\2\5"+
    "\1\11\6\5\51\11\6\5\1\11\1\5\55\0\1\5"+
    "\1\0\1\5\2\0\1\5\2\0\1\5\1\0\10\5"+
    "\33\11\4\5\4\11\15\5\6\0\5\5\1\11\4\5"+
    "\13\0\1\5\1\0\3\5\53\11\37\0\4\5\2\11"+
    "\1\0\143\11\1\5\1\11\10\0\1\5\6\0\2\11"+
    "\2\0\1\5\4\0\2\11\12\0\3\11\2\5\1\11"+
    "\17\5\1\0\1\11\1\0\36\11\33\0\2\5\131\11"+
    "\13\0\1\11\16\5\12\0\41\11\11\0\2\11\4\5"+
    "\1\11\2\5\1\0\30\11\4\0\1\11\11\0\1\11"+
    "\3\0\1\11\5\0\22\5\31\11\3\0\4\5\13\11"+
    "\65\5\25\11\1\5\22\11\13\5\61\0\66\11\3\0"+
    "\1\11\22\0\1\11\7\0\12\11\2\0\2\5\12\0"+
    "\1\5\20\11\3\0\1\5\10\11\2\5\2\11\2\5"+
    "\26\11\1\5\7\11\1\5\1\11\3\5\4\11\2\5"+
    "\1\0\1\11\7\0\2\5\2\0\2\5\3\0\1\11"+
    "\10\5\1\0\4\5\2\11\1\5\3\11\2\0\2\5"+
    "\12\0\4\11\7\5\2\11\1\5\1\0\2\5\3\0"+
    "\1\5\6\11\4\5\2\11\2\5\26\11\1\5\7\11"+
    "\1\5\2\11\1\5\2\11\1\5\2\11\2\5\1\0"+
    "\1\5\5\0\4\5\2\0\2\5\3\0\3\5\1\0"+
    "\7\5\4\11\1\5\1\11\7\5\14\0\3\11\1\0"+
    "\13\5\3\0\1\5\11\11\1\5\3\11\1\5\26\11"+
    "\1\5\7\11\1\5\2\11\1\5\5\11\2\5\1\0"+
    "\1\11\10\0\1\5\3\0\1\5\3\0\2\5\1\11"+
    "\17\5\2\11\2\0\2\5\12\0\1\5\1\11\7\5"+
    "\1\11\6\0\1\5\3\0\1\5\10\11\2\5\2\11"+
    "\2\5\26\11\1\5\7\11\1\5\2\11\1\5\5\11"+
    "\2\5\1\0\1\11\7\0\2\5\2\0\2\5\3\0"+
    "\7\5\3\0\4\5\2\11\1\5\3\11\2\0\2\5"+
    "\12\0\1\5\1\11\20\5\1\0\1\11\1\5\6\11"+
    "\3\5\3\11\1\5\4\11\3\5\2\11\1\5\1\11"+
    "\1\5\2\11\3\5\2\11\3\5\3\11\3\5\14\11"+
    "\4\5\5\0\3\5\3\0\1\5\4\0\2\5\1\11"+
    "\6\5\1\0\16\5\12\0\11\5\1\11\6\5\5\0"+
    "\10\11\1\5\3\11\1\5\27\11\1\5\20\11\3\5"+
    "\1\11\7\0\1\5\3\0\1\5\4\0\7\5\2\0"+
    "\1\5\3\11\5\5\2\11\2\0\2\5\12\0\20\5"+
    "\1\11\3\0\1\5\10\11\1\5\3\11\1\5\27\11"+
    "\1\5\12\11\1\5\5\11\2\5\1\0\1\11\7\0"+
    "\1\5\3\0\1\5\4\0\7\5\2\0\7\5\1\11"+
    "\1\5\2\11\2\0\2\5\12\0\1\5\2\11\15\5"+
    "\4\0\11\11\1\5\3\11\1\5\51\11\2\0\1\11"+
    "\7\0\1\5\3\0\1\5\4\0\1\11\5\5\3\11"+
    "\1\0\7\5\3\11\2\0\2\5\12\0\12\5\6\11"+
    "\1\5\3\0\1\5\22\11\3\5\30\11\1\5\11\11"+
    "\1\5\1\11\2\5\7\11\3\5\1\0\4\5\6\0"+
    "\1\5\1\0\1\5\10\0\6\5\12\0\2\5\2\0"+
    "\15\5\60\11\1\0\2\11\7\0\4\5\10\11\10\0"+
    "\1\5\12\0\47\5\2\11\1\5\1\11\1\5\5\11"+
    "\1\5\30\11\1\5\1\11\1\5\12\11\1\0\2\11"+
    "\11\0\1\11\2\5\5\11\1\5\1\11\1\5\6\0"+
    "\2\5\12\0\2\5\4\11\40\5\1\11\27\5\2\0"+
    "\6\5\12\0\13\5\1\0\1\5\1\0\1\5\1\0"+
    "\4\5\2\0\10\11\1\5\44\11\4\5\24\0\1\5"+
    "\2\0\5\11\13\0\1\5\44\0\11\5\1\0\71\5"+
    "\53\11\24\0\1\11\12\0\6\5\6\11\4\0\4\11"+
    "\3\0\1\11\3\0\2\11\7\0\3\11\4\0\15\11"+
    "\14\0\1\11\17\0\2\5\46\11\1\5\1\11\5\5"+
    "\1\11\2\5\53\11\1\5\115\11\1\5\4\11\2\5"+
    "\7\11\1\5\1\11\1\5\4\11\2\5\51\11\1\5"+
    "\4\11\2\5\41\11\1\5\4\11\2\5\7\11\1\5"+
    "\1\11\1\5\4\11\2\5\17\11\1\5\71\11\1\5"+
    "\4\11\2\5\103\11\2\5\3\0\40\5\20\11\20\5"+
    "\126\11\2\5\6\11\3\5\u016c\11\2\5\21\11\1\5"+
    "\32\11\5\5\113\11\3\5\13\11\7\5\15\11\1\5"+
    "\4\11\3\0\13\5\22\11\3\0\13\5\22\11\2\0"+
    "\14\5\15\11\1\5\3\11\1\5\2\0\14\5\64\11"+
    "\40\0\3\5\1\11\3\5\2\11\1\0\2\5\12\0"+
    "\41\5\4\0\1\5\12\0\6\5\131\11\7\5\5\11"+
    "\2\0\42\11\1\0\1\11\5\5\106\11\12\5\37\11"+
    "\1\5\14\0\4\5\14\0\12\5\12\0\36\11\2\5"+
    "\5\11\13\5\54\11\4\5\32\11\6\5\12\0\46\5"+
    "\27\11\5\0\4\5\65\11\12\0\1\5\35\0\2\5"+
    "\13\0\6\5\12\0\15\5\1\11\10\5\16\0\1\5"+
    "\2\0\77\5\5\0\57\11\21\0\7\11\4\5\12\0"+
    "\21\5\11\0\14\5\3\0\36\11\15\0\2\11\12\0"+
    "\54\11\16\0\14\5\44\11\24\0\10\5\12\0\3\5"+
    "\3\11\12\0\44\11\2\5\11\11\7\5\53\11\2\5"+
    "\3\11\20\5\3\0\1\5\25\0\4\11\1\0\6\11"+
    "\1\0\2\11\3\0\1\11\5\5\300\11\72\0\1\5"+
    "\5\0\26\11\2\5\6\11\2\5\46\11\2\5\6\11"+
    "\2\5\10\11\1\5\1\11\1\5\1\11\1\5\1\11"+
    "\1\5\37\11\2\5\65\11\1\5\7\11\1\5\1\11"+
    "\3\5\3\11\1\5\7\11\3\5\4\11\2\5\6\11"+
    "\4\5\15\11\5\5\3\11\1\5\7\11\16\5\5\0"+
    "\30\5\2\3\5\0\20\5\2\11\23\5\1\11\13\5"+
    "\5\0\1\5\12\0\1\5\1\11\15\5\1\11\20\5"+
    "\15\11\3\5\40\11\20\5\15\0\4\5\1\0\3\5"+
    "\14\0\21\5\1\11\4\5\1\11\2\5\12\11\1\5"+
    "\1\11\3\5\5\11\6\5\1\11\1\5\1\11\1\5"+
    "\1\11\1\5\4\11\1\5\13\11\2\5\4\11\5\5"+
    "\5\11\4\5\1\11\21\5\51\11\u0177\5\57\11\1\5"+
    "\57\11\1\5\205\11\6\5\4\11\3\0\2\11\14\5"+
    "\46\11\1\5\1\11\5\5\1\11\2\5\70\11\7\5"+
    "\1\11\17\5\1\0\27\11\11\5\7\11\1\5\7\11"+
    "\1\5\7\11\1\5\7\11\1\5\7\11\1\5\7\11"+
    "\1\5\7\11\1\5\7\11\1\5\40\0\57\5\1\11"+
    "\325\5\3\11\31\5\11\11\6\0\1\5\5\11\2\5"+
    "\5\11\4\5\126\11\2\5\2\0\2\5\3\11\1\5"+
    "\132\11\1\5\4\11\5\5\53\11\1\5\136\11\21\5"+
    "\40\11\60\5\320\11\100\5\375\11\3\5\215\11\103\5"+
    "\56\11\2\5\15\11\3\5\20\11\12\0\2\11\24\5"+
    "\57\11\1\0\4\5\12\0\1\5\37\11\2\0\120\11"+
    "\2\0\45\5\11\11\2\5\147\11\2\5\65\11\2\5"+
    "\11\11\52\5\15\11\1\0\3\11\1\0\4\11\1\0"+
    "\27\11\5\0\4\5\1\0\13\5\1\11\7\5\64\11"+
    "\14\5\2\0\62\11\22\0\12\5\12\0\6\5\22\0"+
    "\6\11\3\5\1\11\1\5\2\11\13\0\34\11\10\0"+
    "\2\5\27\11\15\0\14\5\35\11\3\5\4\0\57\11"+
    "\16\0\16\5\1\11\12\0\6\5\5\11\1\0\12\11"+
    "\12\0\5\11\1\5\51\11\16\0\11\5\3\11\1\0"+
    "\10\11\2\0\2\5\12\0\6\5\27\11\3\5\1\11"+
    "\3\0\62\11\1\0\1\11\3\0\2\11\2\0\5\11"+
    "\2\0\1\11\1\0\1\11\30\5\3\11\2\5\13\11"+
    "\5\0\2\5\3\11\2\0\12\5\6\11\2\5\6\11"+
    "\2\5\6\11\11\5\7\11\1\5\7\11\1\5\53\11"+
    "\1\5\16\11\6\5\163\11\10\0\1\5\2\0\2\5"+
    "\12\0\6\5\244\11\14\5\27\11\4\5\61\11\4\5"+
    "\u0100\3\156\11\2\5\152\11\46\5\7\11\14\5\5\11"+
    "\5\5\1\11\1\0\12\11\1\5\15\11\1\5\5\11"+
    "\1\5\1\11\1\5\2\11\1\5\2\11\1\5\154\11"+
    "\41\5\153\11\22\5\100\11\2\5\66\11\50\5\15\11"+
    "\3\5\20\0\20\5\20\0\3\5\2\11\30\5\3\11"+
    "\31\5\1\11\6\5\5\11\1\5\207\11\2\5\1\0"+
    "\4\5\1\11\13\5\12\0\7\5\32\11\4\5\1\11"+
    "\1\5\32\11\13\5\131\11\3\5\6\11\2\5\6\11"+
    "\2\5\6\11\2\5\3\11\3\5\2\11\3\5\2\11"+
    "\22\5\3\0\4\5\14\11\1\5\32\11\1\5\23\11"+
    "\1\5\2\11\1\5\17\11\2\5\16\11\42\5\173\11"+
    "\105\5\65\11\210\5\1\0\202\5\35\11\3\5\61\11"+
    "\17\5\1\0\37\5\40\11\15\5\36\11\5\5\46\11"+
    "\5\0\5\5\36\11\2\5\44\11\4\5\10\11\1\5"+
    "\5\11\52\5\236\11\2\5\12\0\6\5\44\11\4\5"+
    "\44\11\4\5\50\11\10\5\64\11\234\5\67\11\11\5"+
    "\26\11\12\5\10\11\230\5\6\11\2\5\1\11\1\5"+
    "\54\11\1\5\2\11\3\5\1\11\2\5\27\11\12\5"+
    "\27\11\11\5\37\11\101\5\23\11\1\5\2\11\12\5"+
    "\26\11\12\5\32\11\106\5\70\11\6\5\2\11\100\5"+
    "\1\11\3\0\1\5\2\0\5\5\4\0\4\11\1\5"+
    "\3\11\1\5\35\11\2\5\3\0\4\5\1\0\40\5"+
    "\35\11\3\5\35\11\43\5\10\11\1\5\34\11\2\0"+
    "\31\5\66\11\12\5\26\11\12\5\23\11\15\5\22\11"+
    "\156\5\111\11\67\5\63\11\15\5\63\11\15\5\44\11"+
    "\4\0\10\5\12\0\u0146\5\52\11\1\5\2\0\3\5"+
    "\2\11\116\5\35\11\12\5\1\11\10\5\26\11\13\0"+
    "\137\5\25\11\33\5\27\11\11\5\3\0\65\11\17\0"+
    "\37\5\12\0\17\5\4\0\55\11\13\0\2\5\1\0"+
    "\17\5\1\0\2\5\31\11\7\5\12\0\6\5\3\0"+
    "\44\11\16\0\1\5\12\0\4\5\1\11\2\0\1\11"+
    "\10\5\43\11\1\0\2\5\1\11\11\5\3\0\60\11"+
    "\16\0\4\11\4\5\4\0\1\5\14\0\1\11\1\5"+
    "\1\11\43\5\22\11\1\5\31\11\14\0\6\5\1\0"+
    "\101\5\7\11\1\5\1\11\1\5\4\11\1\5\17\11"+
    "\1\5\12\11\7\5\57\11\14\0\5\5\12\0\6\5"+
    "\4\0\1\5\10\11\2\5\2\11\2\5\26\11\1\5"+
    "\7\11\1\5\2\11\1\5\5\11\1\5\2\0\1\11"+
    "\7\0\2\5\2\0\2\5\3\0\2\5\1\11\6\5"+
    "\1\0\5\5\5\11\2\0\2\5\7\0\3\5\5\0"+
    "\213\5\65\11\22\0\4\11\5\5\12\0\4\5\1\0"+
    "\3\11\36\5\60\11\24\0\2\11\1\5\1\11\10\5"+
    "\12\0\246\5\57\11\7\0\2\5\11\0\27\5\4\11"+
    "\2\0\42\5\60\11\21\0\3\5\1\11\13\5\12\0"+
    "\46\5\53\11\15\0\1\11\7\5\12\0\66\5\33\11"+
    "\2\5\17\0\4\5\12\0\306\5\54\11\17\0\145\5"+
    "\100\11\12\0\25\5\10\11\2\5\1\11\2\5\10\11"+
    "\1\5\2\11\1\5\30\11\6\0\1\5\2\0\2\5"+
    "\4\0\1\11\1\0\1\11\2\0\14\5\12\0\106\5"+
    "\10\11\2\5\47\11\7\0\2\5\7\0\1\11\1\5"+
    "\1\11\1\0\33\5\1\11\12\0\50\11\7\0\1\11"+
    "\4\0\10\5\1\0\10\5\1\11\13\0\56\11\20\0"+
    "\3\5\1\11\42\5\71\11\7\5\11\11\1\5\45\11"+
    "\10\0\1\5\10\0\1\11\17\5\12\0\30\5\36\11"+
    "\2\5\26\0\1\5\16\0\111\5\7\11\1\5\2\11"+
    "\1\5\46\11\6\0\3\5\1\0\1\5\2\0\1\5"+
    "\7\0\1\11\1\0\10\5\12\0\6\5\6\11\1\5"+
    "\2\11\1\5\40\11\5\0\1\5\2\0\1\5\5\0"+
    "\1\11\7\5\12\0\u0136\5\23\11\4\0\271\5\1\11"+
    "\54\5\4\11\37\5\232\11\146\5\157\11\21\5\304\11"+
    "\274\5\57\11\1\5\11\0\307\5\107\11\271\5\71\11"+
    "\7\5\37\11\1\5\12\0\146\5\36\11\2\5\5\0"+
    "\13\5\60\11\7\0\11\5\4\11\14\5\12\0\11\5"+
    "\25\11\5\5\23\11\260\5\100\11\200\5\113\11\4\5"+
    "\1\0\1\11\67\0\7\5\4\0\15\11\100\5\2\11"+
    "\1\5\1\11\1\0\13\5\2\0\16\5\370\11\10\5"+
    "\326\11\52\5\11\11\367\5\37\11\61\5\3\11\21\5"+
    "\4\11\10\5\u018c\11\4\5\153\11\5\5\15\11\3\5"+
    "\11\11\7\5\12\11\3\5\2\0\1\5\4\0\301\5"+
    "\5\0\3\5\26\0\2\5\7\0\36\5\4\0\224\5"+
    "\3\0\273\5\125\11\1\5\107\11\1\5\2\11\2\5"+
    "\1\11\2\5\2\11\2\5\4\11\1\5\14\11\1\5"+
    "\1\11\1\5\7\11\1\5\101\11\1\5\4\11\2\5"+
    "\10\11\1\5\7\11\1\5\34\11\1\5\4\11\1\5"+
    "\5\11\1\5\1\11\3\5\7\11\1\5\u0154\11\2\5"+
    "\31\11\1\5\31\11\1\5\37\11\1\5\31\11\1\5"+
    "\37\11\1\5\31\11\1\5\37\11\1\5\31\11\1\5"+
    "\37\11\1\5\31\11\1\5\10\11\2\5\151\0\4\5"+
    "\62\0\10\5\1\0\16\5\1\0\26\5\5\0\1\5"+
    "\17\0\120\5\7\0\1\5\21\0\2\5\7\0\1\5"+
    "\2\0\1\5\5\0\325\5\55\11\3\5\7\0\7\11"+
    "\2\5\12\0\4\5\1\11\u0171\5\54\11\16\0\5\5"+
    "\306\11\13\5\7\0\51\5\104\11\7\0\1\11\4\5"+
    "\12\0\u0156\5\1\11\117\5\4\11\1\5\33\11\1\5"+
    "\2\11\1\5\1\11\2\5\1\11\1\5\12\11\1\5"+
    "\4\11\1\5\1\11\1\5\1\11\6\5\1\11\4\5"+
    "\1\11\1\5\1\11\1\5\1\11\1\5\3\11\1\5"+
    "\2\11\1\5\1\11\2\5\1\11\1\5\1\11\1\5"+
    "\1\11\1\5\1\11\1\5\1\11\1\5\2\11\1\5"+
    "\1\11\2\5\4\11\1\5\7\11\1\5\4\11\1\5"+
    "\4\11\1\5\1\11\1\5\12\11\1\5\21\11\5\5"+
    "\3\11\1\5\5\11\1\5\21\11\u0134\5\12\0\6\5"+
    "\336\11\42\5\65\11\13\5\336\11\2\5\u0182\11\16\5"+
    "\u0131\11\37\5\36\11\342\5\113\11\266\5\1\0\36\5"+
    "\140\0\200\5\360\0\20\5";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[31232];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\17\5\1\30\1\31\2\4\1\0\1\31"+
    "\2\0\1\32\1\33\1\34\1\35\1\36\1\37\7\5"+
    "\1\40\5\5\1\41\7\5\1\0\1\4\1\42\1\0"+
    "\1\42\1\43\3\5\1\44\1\5\1\45\3\5\1\46"+
    "\1\5\1\47\5\5\1\50\1\5\2\0\1\51\1\5"+
    "\1\52\2\5\1\53\1\54\1\55\1\56\2\5\1\57"+
    "\1\60\1\5\1\4\1\5\1\61\3\5\1\62\2\5"+
    "\1\63\1\64\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\237\0\324\0\u0109\0\u013e"+
    "\0\65\0\65\0\u0173\0\65\0\65\0\65\0\65\0\65"+
    "\0\65\0\65\0\u01a8\0\u01dd\0\65\0\u0212\0\65\0\u0247"+
    "\0\u027c\0\65\0\65\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385"+
    "\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d"+
    "\0\u0562\0\u0597\0\65\0\65\0\u05cc\0\u0601\0\u0173\0\u0173"+
    "\0\u0636\0\u066b\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u013e"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u013e\0\u091c\0\u0951"+
    "\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u013e\0\u0b98\0\u0bcd\0\u0c02\0\u013e\0\u0c37"+
    "\0\u013e\0\u0c6c\0\u0ca1\0\u0cd6\0\u013e\0\u0d0b\0\u013e\0\u0d40"+
    "\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u013e\0\u0e49\0\u0e7e\0\u0b63"+
    "\0\u013e\0\u0eb3\0\u013e\0\u0ee8\0\u0f1d\0\u013e\0\u013e\0\u013e"+
    "\0\u013e\0\u0f52\0\u0f87\0\u013e\0\u013e\0\u0fbc\0\u0a8f\0\u0ff1"+
    "\0\u013e\0\u1026\0\u105b\0\u1090\0\u013e\0\u10c5\0\u10fa\0\u013e"+
    "\0\u013e\0\u013e\0\u013e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\3\1\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\2\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\10\1\33\1\10"+
    "\1\34\1\35\1\36\1\37\1\40\2\10\1\41\1\42"+
    "\1\43\1\44\1\45\1\10\1\46\1\47\1\50\1\10"+
    "\1\51\1\52\1\4\1\2\67\0\1\4\60\0\1\4"+
    "\32\0\1\53\33\0\7\6\1\54\55\6\2\55\3\0"+
    "\12\55\1\56\44\55\1\0\1\10\10\0\1\10\13\0"+
    "\1\10\7\0\1\10\1\0\24\10\1\0\1\10\7\57"+
    "\1\0\4\57\1\60\50\57\23\0\1\61\1\0\1\23"+
    "\7\0\1\62\60\0\1\63\64\0\1\64\64\0\1\65"+
    "\54\0\1\66\1\0\1\67\2\0\1\70\36\0\1\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\13\10"+
    "\1\71\10\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\14\10\1\72\7\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\10\10"+
    "\1\73\13\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\11\10\1\74\1\10\1\75\10\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\1\10\1\76\17\10\1\77\2\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\5\10"+
    "\1\100\5\10\1\101\10\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\14\10\1\102\7\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\1\10\1\103\22\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\14\10\1\104\4\10"+
    "\1\105\2\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\16\10\1\106\2\10\1\107\2\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\4\10\1\110\17\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\20\10\1\111\3\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\7\10\1\112\6\10\1\113\5\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\1\10"+
    "\1\114\22\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\7\10\1\115\14\10\1\0\1\10"+
    "\2\55\3\0\57\55\1\0\2\56\3\116\12\56\1\117"+
    "\44\56\1\116\25\0\1\120\57\0\1\121\4\0\1\122"+
    "\37\0\1\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\3\10\1\123\20\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\14\10\1\124\7\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\22\10\1\125\1\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\17\10\1\126\4\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\3\10\1\127\20\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\11\10\1\130\12\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\13\10\1\131\10\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\20\10\1\132\3\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\14\10\1\133\7\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\10\10\1\134\13\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\20\10\1\135\3\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\11\10\1\136\12\10"+
    "\1\0\2\10\10\0\1\10\13\0\1\10\7\0\1\10"+
    "\1\0\20\10\1\137\3\10\1\0\2\10\10\0\1\10"+
    "\13\0\1\10\7\0\1\10\1\0\1\10\1\140\16\10"+
    "\1\141\3\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\16\10\1\142\5\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\4\10"+
    "\1\143\17\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\21\10\1\144\2\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\16\10"+
    "\1\145\5\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\10\10\1\146\13\10\1\0\1\10"+
    "\17\116\1\147\45\116\2\56\3\116\12\56\1\117\4\56"+
    "\1\55\37\56\1\116\25\0\1\120\7\0\1\62\51\0"+
    "\1\150\67\0\1\122\37\0\1\10\10\0\1\10\13\0"+
    "\1\10\7\0\1\10\1\0\11\10\1\151\12\10\1\0"+
    "\2\10\10\0\1\10\13\0\1\10\7\0\1\10\1\0"+
    "\1\152\23\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\4\10\1\153\17\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\17\10"+
    "\1\154\4\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\4\10\1\155\17\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\15\10"+
    "\1\156\6\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\13\10\1\157\10\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\11\10"+
    "\1\160\12\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\11\10\1\161\12\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\21\10"+
    "\1\162\2\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\10\10\1\163\13\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\13\10"+
    "\1\164\10\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\4\10\1\165\17\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\11\10"+
    "\1\166\12\10\1\0\1\10\10\116\1\167\6\116\1\147"+
    "\4\116\1\0\40\116\1\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\10\10\1\170\13\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\4\10"+
    "\1\171\17\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\6\10\1\172\15\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\16\10"+
    "\1\173\5\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\13\10\1\174\10\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\4\10"+
    "\1\175\17\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\13\10\1\176\10\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\4\10"+
    "\1\177\17\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\13\10\1\200\10\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\6\10"+
    "\1\201\15\10\1\0\2\10\10\0\1\10\13\0\1\10"+
    "\7\0\1\10\1\0\20\10\1\202\3\10\1\0\2\10"+
    "\10\0\1\10\13\0\1\10\7\0\1\10\1\0\16\10"+
    "\1\203\5\10\1\0\1\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4399];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\2\11\1\1\7\11\2\1\1\11"+
    "\1\1\1\11\2\1\2\11\17\1\2\11\2\1\1\0"+
    "\1\1\2\0\6\11\25\1\1\0\2\1\1\0\25\1"+
    "\2\0\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type)
	{
		return new Symbol(type);
	}

	private Symbol symbol(int type, String value)
	{
		Symbol toReturn;
		toReturn = new Symbol(type, yyline, yycolumn, value);
		return toReturn;
	}

      private void error(String message) {
        System.out.println("Line:"+(yyline+1)+" Column:"+(yycolumn+1)+message);
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Token.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+"> at line "+yyline+", column "+yycolumn);
            }
            // fall through
          case 55: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 56: break;
          case 3:
            { error("stringa non chiusa");
            }
            // fall through
          case 57: break;
          case 4:
            { 
            }
            // fall through
          case 58: break;
          case 5:
            { return symbol(Token.ID, yytext());
            }
            // fall through
          case 59: break;
          case 6:
            { return symbol(Token.READ, yytext());
            }
            // fall through
          case 60: break;
          case 7:
            { return symbol(Token.STR_CONCAT, yytext());
            }
            // fall through
          case 61: break;
          case 8:
            { return symbol(Token.LPAR, yytext());
            }
            // fall through
          case 62: break;
          case 9:
            { return symbol(Token.RPAR, yytext());
            }
            // fall through
          case 63: break;
          case 10:
            { return symbol(Token.TIMES, yytext());
            }
            // fall through
          case 64: break;
          case 11:
            { return symbol(Token.PLUS, yytext());
            }
            // fall through
          case 65: break;
          case 12:
            { return symbol(Token.COMMA, yytext());
            }
            // fall through
          case 66: break;
          case 13:
            { return symbol(Token.MINUS, yytext());
            }
            // fall through
          case 67: break;
          case 14:
            { return symbol(Token.DIV, yytext());
            }
            // fall through
          case 68: break;
          case 15:
            { return symbol(Token.NUMBER_INT, yytext());
            }
            // fall through
          case 69: break;
          case 16:
            { return symbol(Token.COLON, yytext());
            }
            // fall through
          case 70: break;
          case 17:
            { return symbol(Token.SEMI, yytext());
            }
            // fall through
          case 71: break;
          case 18:
            { return symbol(Token.LT, yytext());
            }
            // fall through
          case 72: break;
          case 19:
            { return symbol(Token.EQ, yytext());
            }
            // fall through
          case 73: break;
          case 20:
            { return symbol(Token.GT, yytext());
            }
            // fall through
          case 74: break;
          case 21:
            { return symbol(Token.WRITE, yytext());
            }
            // fall through
          case 75: break;
          case 22:
            { return symbol(Token.OUTPAR, yytext());
            }
            // fall through
          case 76: break;
          case 23:
            { return symbol(Token.POW, yytext());
            }
            // fall through
          case 77: break;
          case 24:
            { return symbol(Token.NE, yytext());
            }
            // fall through
          case 78: break;
          case 25:
            { return symbol(Token.STRING_CONST, yytext());
            }
            // fall through
          case 79: break;
          case 26:
            { return symbol(Token.ASSIGN, yytext());
            }
            // fall through
          case 80: break;
          case 27:
            { return symbol(Token.LE, yytext());
            }
            // fall through
          case 81: break;
          case 28:
            { return symbol(Token.GE, yytext());
            }
            // fall through
          case 82: break;
          case 29:
            { return symbol(Token.WRITEB, yytext());
            }
            // fall through
          case 83: break;
          case 30:
            { return symbol(Token.WRITELN, yytext());
            }
            // fall through
          case 84: break;
          case 31:
            { return symbol(Token.WRITET, yytext());
            }
            // fall through
          case 85: break;
          case 32:
            { return symbol(Token.IF, yytext());
            }
            // fall through
          case 86: break;
          case 33:
            { return symbol(Token.OR, yytext());
            }
            // fall through
          case 87: break;
          case 34:
            { return symbol(Token.NUMBER_REAL, yytext());
            }
            // fall through
          case 88: break;
          case 35:
            { return symbol(Token.AND, yytext());
            }
            // fall through
          case 89: break;
          case 36:
            { return symbol(Token.END, yytext());
            }
            // fall through
          case 90: break;
          case 37:
            { return symbol(Token.FUN, yytext());
            }
            // fall through
          case 91: break;
          case 38:
            { return symbol(Token.NOT, yytext());
            }
            // fall through
          case 92: break;
          case 39:
            { return symbol(Token.OUT, yytext());
            }
            // fall through
          case 93: break;
          case 40:
            { return symbol(Token.VAR, yytext());
            }
            // fall through
          case 94: break;
          case 41:
            { return symbol(Token.BOOL, yytext());
            }
            // fall through
          case 95: break;
          case 42:
            { return symbol(Token.ELSE, yytext());
            }
            // fall through
          case 96: break;
          case 43:
            { return symbol(Token.LOOP, yytext());
            }
            // fall through
          case 97: break;
          case 44:
            { return symbol(Token.MAIN, yytext());
            }
            // fall through
          case 98: break;
          case 45:
            { return symbol(Token.NULL, yytext());
            }
            // fall through
          case 99: break;
          case 46:
            { return symbol(Token.REAL, yytext());
            }
            // fall through
          case 100: break;
          case 47:
            { return symbol(Token.THEN, yytext());
            }
            // fall through
          case 101: break;
          case 48:
            { return symbol(Token.TRUE, yytext());
            }
            // fall through
          case 102: break;
          case 49:
            { return symbol(Token.FALSE, yytext());
            }
            // fall through
          case 103: break;
          case 50:
            { return symbol(Token.WHILE, yytext());
            }
            // fall through
          case 104: break;
          case 51:
            { return symbol(Token.RETURN, yytext());
            }
            // fall through
          case 105: break;
          case 52:
            { return symbol(Token.STRING, yytext());
            }
            // fall through
          case 106: break;
          case 53:
            { return symbol(Token.DIVINT, yytext());
            }
            // fall through
          case 107: break;
          case 54:
            { return symbol(Token.INTEGER, yytext());
            }
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
